background #0e1415
foreground #dee3e5
selection_background #82d3e0
selection_foreground #00363d
cursor #82d3e0
color0 #0e1415
color8 #3f484a
color1 #ffb4ab
color9 #93000a
color2 #bac6ea
color10 #3b4664
color3 #b1cbd0
color11 #334b4f
color4 #82d3e0
color12 #004f58
color5 #bac6ea
color13 #dae2ff
color6 #b1cbd0
color14 #cde7ec
color7 #dee3e5
color15 #dee3e5
