[config]
mode = "dark"
scheme_type = "scheme-content"

[templates.hyprland]
input_path = "/home/aqua/.config/matugen/templates/hyprland.conf.template"
output_path = "/home/aqua/nixos-dots/home/dotfiles/hyprland/colors.conf"

[templates.quickshell]
input_path = "/home/aqua/.config/matugen/templates/quickshell.json.template"
output_path = "/tmp/qs_colors.json"
