$primary = rgb(82d3e0)
$onPrimary = rgb(00363d)
$primaryContainer = rgb(004f58)
$secondary = rgb(b1cbd0)
$tertiary = rgb(bac6ea)
$surface = rgb(0e1415)
$onSurface = rgb(dee3e5)
$surfaceVariant = rgb(3f484a)
$outline = rgb(899294)
$error = rgb(ffb4ab)
$background = rgb(0e1415)
