$primary = rgb(373900)
$onPrimary = rgb(ffffff)
$primaryContainer = rgb(6e7200)
$secondary = rgb(373902)
$tertiary = rgb(084000)
$surface = rgb(fdfae9)
$onSurface = rgb(111208)
$surfaceVariant = rgb(e5e4ca)
$outline = rgb(535440)
$error = rgb(740006)
$background = rgb(fdfae9)
