$primary = rgb(c0e4de)
$onPrimary = rgb(062b27)
$primaryContainer = rgb(759792)
$secondary = rgb(d1dfdc)
$tertiary = rgb(e3d7f7)
$surface = rgb(121413)
$onSurface = rgb(ffffff)
$surfaceVariant = rgb(414847)
$outline = rgb(acb3b1)
$error = rgb(ffd2cc)
$background = rgb(121413)
