source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/colors.conf

monitor = ,1920x1080@144,auto,1

exec-once = awww-daemon
exec-once = bash -c 'sleep 1 && WALL=$(cat ~/.cache/current-wallpaper 2>/dev/null || echo ~/nixos-dots/home/dotfiles/wallpapers/awallpaper1.jpg); MODE=$(cat ~/.cache/current-theme-mode 2>/dev/null || echo dark); ~/scripts/wallpaper.sh "$WALL" "$MODE"'
exec-once = wl-paste --type text --watch cliphist store
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = qs
exec-once = hypridle

general {
  gaps_in             = 6
  gaps_out            = 12
  border_size         = 2
  col.active_border   = $primary $tertiary 45deg
  col.inactive_border = $surfaceVariant
  layout              = scrolling
  resize_on_border    = true
  allow_tearing       = false
}

decoration {
  rounding         = 12
  active_opacity   = 1.0
  inactive_opacity = 1.0

  shadow {
    enabled      = true
    range        = 20
    render_power = 3
    color        = rgba(0,0,0,0.4)
  }

  blur {
    enabled           = true
    size              = 5
    passes            = 2
    new_optimizations = true
    xray              = false
    popups            = false
  }
}

input {
  kb_layout    = us
  follow_mouse = 1
  sensitivity  = 0

  touchpad {
    natural_scroll = true
    tap-to-click   = true
    drag_lock      = true
    scroll_factor  = 0.5
  }
}

misc {
  force_default_wallpaper      = 0
  disable_hyprland_logo        = true
  animate_mouse_windowdragging = false
}

dwindle {
  preserve_split = true
}
