windowrule = float class:(org.gnome.Nautilus)
windowrule = size 960 540 class:(org.gnome.Nautilus)
windowrule = center class:(org.gnome.Nautilus)
windowrule = float class:(pavucontrol)
windowrule = float class:(blueman-manager)
windowrule = float class:(nm-connection-editor)
windowrule = float class:(gnome-calculator)
windowrule = float class:(org.gnome.Loupe)
windowrule = float class:(impala)
windowrule = float title:(Open File)
windowrule = float title:(Save As)
windowrule = float title:(Picture-in-Picture)
windowrule = float title:(nmtui)
windowrule = float class:(nmtui)

windowrule = size 960 540 class:(pavucontrol)
windowrule = center class:(pavucontrol)
windowrule = size 960 540 class:(blueman-manager)
windowrule = center class:(blueman-manager)
windowrule = size 960 540 class:(nm-connection-editor)
windowrule = center class:(nm-connection-editor)
windowrule = size 960 540 class:(gnome-calculator)
windowrule = center class:(gnome-calculator)
windowrule = size 960 540 class:(org.gnome.Loupe)
windowrule = center class:(org.gnome.Loupe)
windowrule = size 960 540 title:(nmtui)
windowrule = center title:(nmtui)
windowrule = size 960 540 class:(nmtui)
windowrule = center class:(nmtui)
windowrule = size 960 540 title:(Open File)
windowrule = center title:(Open File)
windowrule = size 960 540 title:(Save As)
windowrule = center title:(Save As)

windowrule = pin title:(Picture-in-Picture)
windowrule = size 400 250 title:(Picture-in-Picture)
windowrule = move 100%-410 100%-260 title:(Picture-in-Picture)

layerrule = blur namespace:(quickshell.*)
