windowrule = float class:(pavucontrol)
windowrule = float class:(blueman-manager)
windowrule = float class:(nm-connection-editor)
windowrule = float class:(gnome-calculator)
windowrule = float class:(org.gnome.Loupe)
windowrule = float class:(impala)
windowrule = float title:(Open File)
windowrule = float title:(Save As)
windowrule = float title:(Picture-in-Picture)
windowrule = pin title:(Picture-in-Picture)
layerrule = blur namespace:(quickshell.*)
